//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentacion.WCFServicio {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFServicio.IServicios")]
    public interface IServicios {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/AgregarUsuario", ReplyAction="http://tempuri.org/IServicios/AgregarUsuarioResponse")]
        int AgregarUsuario(Entidades.Usuarios P_Usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/AgregarUsuario", ReplyAction="http://tempuri.org/IServicios/AgregarUsuarioResponse")]
        System.Threading.Tasks.Task<int> AgregarUsuarioAsync(Entidades.Usuarios P_Usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/ModificarUsuario", ReplyAction="http://tempuri.org/IServicios/ModificarUsuarioResponse")]
        int ModificarUsuario(Entidades.Usuarios P_Usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/ModificarUsuario", ReplyAction="http://tempuri.org/IServicios/ModificarUsuarioResponse")]
        System.Threading.Tasks.Task<int> ModificarUsuarioAsync(Entidades.Usuarios P_Usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/EliminarUsuario", ReplyAction="http://tempuri.org/IServicios/EliminarUsuarioResponse")]
        int EliminarUsuario(Entidades.Usuarios P_Usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/EliminarUsuario", ReplyAction="http://tempuri.org/IServicios/EliminarUsuarioResponse")]
        System.Threading.Tasks.Task<int> EliminarUsuarioAsync(Entidades.Usuarios P_Usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/AgregarCliente", ReplyAction="http://tempuri.org/IServicios/AgregarClienteResponse")]
        int AgregarCliente(Entidades.Clientes P_Cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/AgregarCliente", ReplyAction="http://tempuri.org/IServicios/AgregarClienteResponse")]
        System.Threading.Tasks.Task<int> AgregarClienteAsync(Entidades.Clientes P_Cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/ModificarCliente", ReplyAction="http://tempuri.org/IServicios/ModificarClienteResponse")]
        int ModificarCliente(Entidades.Clientes P_Cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/ModificarCliente", ReplyAction="http://tempuri.org/IServicios/ModificarClienteResponse")]
        System.Threading.Tasks.Task<int> ModificarClienteAsync(Entidades.Clientes P_Cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/EliminarCliente", ReplyAction="http://tempuri.org/IServicios/EliminarClienteResponse")]
        int EliminarCliente(Entidades.Clientes P_Cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/EliminarCliente", ReplyAction="http://tempuri.org/IServicios/EliminarClienteResponse")]
        System.Threading.Tasks.Task<int> EliminarClienteAsync(Entidades.Clientes P_Cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/AgregarPrestamo", ReplyAction="http://tempuri.org/IServicios/AgregarPrestamoResponse")]
        void AgregarPrestamo(Entidades.Prestamos P_Prestamo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/AgregarPrestamo", ReplyAction="http://tempuri.org/IServicios/AgregarPrestamoResponse")]
        System.Threading.Tasks.Task AgregarPrestamoAsync(Entidades.Prestamos P_Prestamo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/VerificarUsuario", ReplyAction="http://tempuri.org/IServicios/VerificarUsuarioResponse")]
        System.Collections.Generic.List<Entidades.Usuarios> VerificarUsuario(Entidades.Usuarios P_Usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/VerificarUsuario", ReplyAction="http://tempuri.org/IServicios/VerificarUsuarioResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.Usuarios>> VerificarUsuarioAsync(Entidades.Usuarios P_Usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/ConsultarPrestamosPorCliente", ReplyAction="http://tempuri.org/IServicios/ConsultarPrestamosPorClienteResponse")]
        System.Collections.Generic.List<Entidades.Prestamos> ConsultarPrestamosPorCliente(Entidades.Prestamos P_Prestamo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/ConsultarPrestamosPorCliente", ReplyAction="http://tempuri.org/IServicios/ConsultarPrestamosPorClienteResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.Prestamos>> ConsultarPrestamosPorClienteAsync(Entidades.Prestamos P_Prestamo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/ConsultarPrestamosPorEstado", ReplyAction="http://tempuri.org/IServicios/ConsultarPrestamosPorEstadoResponse")]
        System.Collections.Generic.List<Entidades.Prestamos> ConsultarPrestamosPorEstado(Entidades.Prestamos P_Prestamo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/ConsultarPrestamosPorEstado", ReplyAction="http://tempuri.org/IServicios/ConsultarPrestamosPorEstadoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.Prestamos>> ConsultarPrestamosPorEstadoAsync(Entidades.Prestamos P_Prestamo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/ConsultarUsuarios", ReplyAction="http://tempuri.org/IServicios/ConsultarUsuariosResponse")]
        System.Collections.Generic.List<Entidades.Usuarios> ConsultarUsuarios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/ConsultarUsuarios", ReplyAction="http://tempuri.org/IServicios/ConsultarUsuariosResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.Usuarios>> ConsultarUsuariosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/ConsultarClientes", ReplyAction="http://tempuri.org/IServicios/ConsultarClientesResponse")]
        System.Collections.Generic.List<Entidades.Clientes> ConsultarClientes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/ConsultarClientes", ReplyAction="http://tempuri.org/IServicios/ConsultarClientesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.Clientes>> ConsultarClientesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/EnviarCorreoElectronico", ReplyAction="http://tempuri.org/IServicios/EnviarCorreoElectronicoResponse")]
        void EnviarCorreoElectronico(Entidades.Correo P_Correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/EnviarCorreoElectronico", ReplyAction="http://tempuri.org/IServicios/EnviarCorreoElectronicoResponse")]
        System.Threading.Tasks.Task EnviarCorreoElectronicoAsync(Entidades.Correo P_Correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/VerificarEmailUsuario", ReplyAction="http://tempuri.org/IServicios/VerificarEmailUsuarioResponse")]
        System.Collections.Generic.List<Entidades.Usuarios> VerificarEmailUsuario(Entidades.Usuarios P_Usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/VerificarEmailUsuario", ReplyAction="http://tempuri.org/IServicios/VerificarEmailUsuarioResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.Usuarios>> VerificarEmailUsuarioAsync(Entidades.Usuarios P_Usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/ActualizarPrestamo", ReplyAction="http://tempuri.org/IServicios/ActualizarPrestamoResponse")]
        void ActualizarPrestamo(Entidades.Prestamos P_Prestamo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicios/ActualizarPrestamo", ReplyAction="http://tempuri.org/IServicios/ActualizarPrestamoResponse")]
        System.Threading.Tasks.Task ActualizarPrestamoAsync(Entidades.Prestamos P_Prestamo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiciosChannel : Presentacion.WCFServicio.IServicios, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiciosClient : System.ServiceModel.ClientBase<Presentacion.WCFServicio.IServicios>, Presentacion.WCFServicio.IServicios {
        
        public ServiciosClient() {
        }
        
        public ServiciosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiciosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiciosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiciosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int AgregarUsuario(Entidades.Usuarios P_Usuario) {
            return base.Channel.AgregarUsuario(P_Usuario);
        }
        
        public System.Threading.Tasks.Task<int> AgregarUsuarioAsync(Entidades.Usuarios P_Usuario) {
            return base.Channel.AgregarUsuarioAsync(P_Usuario);
        }
        
        public int ModificarUsuario(Entidades.Usuarios P_Usuario) {
            return base.Channel.ModificarUsuario(P_Usuario);
        }
        
        public System.Threading.Tasks.Task<int> ModificarUsuarioAsync(Entidades.Usuarios P_Usuario) {
            return base.Channel.ModificarUsuarioAsync(P_Usuario);
        }
        
        public int EliminarUsuario(Entidades.Usuarios P_Usuario) {
            return base.Channel.EliminarUsuario(P_Usuario);
        }
        
        public System.Threading.Tasks.Task<int> EliminarUsuarioAsync(Entidades.Usuarios P_Usuario) {
            return base.Channel.EliminarUsuarioAsync(P_Usuario);
        }
        
        public int AgregarCliente(Entidades.Clientes P_Cliente) {
            return base.Channel.AgregarCliente(P_Cliente);
        }
        
        public System.Threading.Tasks.Task<int> AgregarClienteAsync(Entidades.Clientes P_Cliente) {
            return base.Channel.AgregarClienteAsync(P_Cliente);
        }
        
        public int ModificarCliente(Entidades.Clientes P_Cliente) {
            return base.Channel.ModificarCliente(P_Cliente);
        }
        
        public System.Threading.Tasks.Task<int> ModificarClienteAsync(Entidades.Clientes P_Cliente) {
            return base.Channel.ModificarClienteAsync(P_Cliente);
        }
        
        public int EliminarCliente(Entidades.Clientes P_Cliente) {
            return base.Channel.EliminarCliente(P_Cliente);
        }
        
        public System.Threading.Tasks.Task<int> EliminarClienteAsync(Entidades.Clientes P_Cliente) {
            return base.Channel.EliminarClienteAsync(P_Cliente);
        }
        
        public void AgregarPrestamo(Entidades.Prestamos P_Prestamo) {
            base.Channel.AgregarPrestamo(P_Prestamo);
        }
        
        public System.Threading.Tasks.Task AgregarPrestamoAsync(Entidades.Prestamos P_Prestamo) {
            return base.Channel.AgregarPrestamoAsync(P_Prestamo);
        }
        
        public System.Collections.Generic.List<Entidades.Usuarios> VerificarUsuario(Entidades.Usuarios P_Usuario) {
            return base.Channel.VerificarUsuario(P_Usuario);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.Usuarios>> VerificarUsuarioAsync(Entidades.Usuarios P_Usuario) {
            return base.Channel.VerificarUsuarioAsync(P_Usuario);
        }
        
        public System.Collections.Generic.List<Entidades.Prestamos> ConsultarPrestamosPorCliente(Entidades.Prestamos P_Prestamo) {
            return base.Channel.ConsultarPrestamosPorCliente(P_Prestamo);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.Prestamos>> ConsultarPrestamosPorClienteAsync(Entidades.Prestamos P_Prestamo) {
            return base.Channel.ConsultarPrestamosPorClienteAsync(P_Prestamo);
        }
        
        public System.Collections.Generic.List<Entidades.Prestamos> ConsultarPrestamosPorEstado(Entidades.Prestamos P_Prestamo) {
            return base.Channel.ConsultarPrestamosPorEstado(P_Prestamo);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.Prestamos>> ConsultarPrestamosPorEstadoAsync(Entidades.Prestamos P_Prestamo) {
            return base.Channel.ConsultarPrestamosPorEstadoAsync(P_Prestamo);
        }
        
        public System.Collections.Generic.List<Entidades.Usuarios> ConsultarUsuarios() {
            return base.Channel.ConsultarUsuarios();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.Usuarios>> ConsultarUsuariosAsync() {
            return base.Channel.ConsultarUsuariosAsync();
        }
        
        public System.Collections.Generic.List<Entidades.Clientes> ConsultarClientes() {
            return base.Channel.ConsultarClientes();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.Clientes>> ConsultarClientesAsync() {
            return base.Channel.ConsultarClientesAsync();
        }
        
        public void EnviarCorreoElectronico(Entidades.Correo P_Correo) {
            base.Channel.EnviarCorreoElectronico(P_Correo);
        }
        
        public System.Threading.Tasks.Task EnviarCorreoElectronicoAsync(Entidades.Correo P_Correo) {
            return base.Channel.EnviarCorreoElectronicoAsync(P_Correo);
        }
        
        public System.Collections.Generic.List<Entidades.Usuarios> VerificarEmailUsuario(Entidades.Usuarios P_Usuario) {
            return base.Channel.VerificarEmailUsuario(P_Usuario);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.Usuarios>> VerificarEmailUsuarioAsync(Entidades.Usuarios P_Usuario) {
            return base.Channel.VerificarEmailUsuarioAsync(P_Usuario);
        }
        
        public void ActualizarPrestamo(Entidades.Prestamos P_Prestamo) {
            base.Channel.ActualizarPrestamo(P_Prestamo);
        }
        
        public System.Threading.Tasks.Task ActualizarPrestamoAsync(Entidades.Prestamos P_Prestamo) {
            return base.Channel.ActualizarPrestamoAsync(P_Prestamo);
        }
    }
}
